
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyyexbyqjrasipkxezpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5eWV4YnlxanJhc2lwa3hlenBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDM4MjksImV4cCI6MjA2NTQ3OTgyOX0.K_6nwFfaNWG_MkY9qSdbDMeq1emoq7O3P5zYydMjUKM";

// Configuration optimisée pour éviter les problèmes de connexion
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'implicit'
  },
  global: {
    headers: {
      'x-client-info': 'transport-manager-web'
    }
  }
});
